services:
  llm-benchmarker-master:
    image: locustio/locust:2.31.2
    command: >
      --master
      --host=https://chat.lab.tt
    environment:
      LOCUST_API_KEY: "${OPENWEBUI_API_KEY}"
      TARGET_MODEL: "${TARGET_MODEL}"
    ports:
      - 8089:8089
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    restart: unless-stopped
    working_dir: /mnt/locust
  locust-worker:
    image: locustio/locust:2.31.2
    command: >
      --worker
      --master-host=llm-benchmarker-master
    environment:
      LOCUST_API_KEY: "${OPENWEBUI_API_KEY}"
      TARGET_MODEL: "${TARGET_MODEL}"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    working_dir: /mnt/locust
    depends_on:
      - llm-benchmarker-master
